### ISSUE TITLE
color is incorrect in Linux (Ubuntu 16.04 on Parallels VM on OS X host) 

### ISSUE THREAD

**Issue by DavidLudwig** [DavidLudwig/macemu#16]
<img width="619" alt="screen shot 2017-08-14 at 12 30 00 pm" src="https://user-images.githubusercontent.com/475856/29281271-550601fc-80ec-11e7-8dc2-ce700919a7c5.png">

**Comment by DavidLudwig** [comment]
Millions of Colors is now working, however Thousands of Colors is (still?) displaying incorrectly.  Screenshot attached.
<img width="640" alt="screen shot 2017-08-14 at 1 27 08 pm" src="https://user-images.githubusercontent.com/475856/29283362-6c00c178-80f4-11e7-9fd7-501bae9ce60e.png">

**Comment by DavidLudwig** [comment]
For reference, here is what Millions of Colors looks like, via the same (internal) build:
<img width="618" alt="screen shot 2017-08-14 at 1 30 42 pm" src="https://user-images.githubusercontent.com/475856/29283476-d7dcb942-80f4-11e7-8f5b-8cbb5fc45685.png">

**Comment by rickyzhang82** [comment]
@DavidLudwig If you want to test GNU automake build, you can install Macports or Homebrew to install gtk2 and SDL2. GNU automake is the only way I used to build BII in Mac OSX. See wiki: https://github.com/cebix/macemu/wiki/Basilisk-II-Compilation-Guide

**Comment by rickyzhang82** [comment]
@DavidLudwig In upstream macemu repository master branch, if I force to use mem bank addressing in Linux with the following configure:
```bash
./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon --enable-addressing=banks
```
I saw the yellowish screen. This didn't happens in Mac OS X which uses mem bank addressing nor in Linux with direct addressing.

Do you understand why it happens? Note that my observation is based on SDL1 in macemu upstream. It is not SDL2 in yours.
