### ISSUE TITLE
GTK preference UI was broken in both Linux and Mac OS X

### ISSUE THREAD

**Issue by rickyzhang82** [DavidLudwig/macemu#20]
I used GNU automake build
```bash
cd macemu/BasiliskII/src/Unix/
make clean
NO_CONFIGURE=1 ./autogen.sh
./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk
make -j 32
```

Run
```bash
./BasiliskII
```

It brings up a blank preference UI. What's the worse -- it delete my preference file under ~/.basilisk_ii_prefs.

**Comment by DavidLudwig** [comment]
I am wondering if this was already a bug in Basilisk, or if it is a new
one, introduced by the SDL2 changes.

If you try the same build commands using the repository at
https://github.com/cebix/macemu, does Basilisk II behave differently?

**Comment by rickyzhang82** [comment]
It is a new bug. It works fine in automake build under Linux and Mac OS X from upstream macemu repo.

**Comment by rickyzhang82** [comment]
@DavidLudwig Since you built Windows, I wonder if the preference UI is a GTK application in Windows as well.

The reason I ask is to decide if we should maintain GTK or find another way to implement it so that it works in Linux, Mac and Windows.

**Comment by DavidLudwig** [comment]
I am unsure of the structure of the GTK setup app.

I am a bit inclined to, eventually, and not until reasonably finishing the SDL2 port, rewriting the GUI, using less dependencies.  I am unsure of this, though.

**Comment by rickyzhang82** [comment]
That's correct. Porting SDL2 may have a lot work.

**Comment by DavidLudwig** [comment]
Fixed in https://github.com/DavidLudwig/macemu/commit/dbd997fa47f3507946d88a341e041b0bb1a1d81c
