### ISSUE TITLE
Keep SDL 1.x code in place

### ISSUE THREAD

**Issue by DavidLudwig** [DavidLudwig/macemu#30]
A request came up on the main, macemu repository, to keep the SDL 1.x code in-place, for the time being.

To-do, among other things:
- move SDL2-using video code to video_sdl2.cpp
- restore SDL1 to video_sdl.cpp
- add compile-time checks for SDL version, to video_sdl*.cpp.  (Both SDL 1.x and 2.x have macros that could be used here)
- make sure audio_sdl.cpp works with SDL 1.x, or split audio backends into two files (audio_sdl2.cpp and audio_sdl.cpp).  (A recent change, https://github.com/DavidLudwig/macemu/commit/d5e68ceebfa899b5a78b784c543cd99acab0346d, switched come SDL audio calls to SDL2 variants.
- make sure Autotools can work with both SDL 1.x and SDL 2.x.

**Comment by kencu** [comment]
If I might ask for a way to force SDL1 or SDL2 for the many systems that might have both installed. I'm sure you were already going to do this. Or make it to always default to SDL2 unless --with-sdl1 is passed in, for example.

**Comment by DavidLudwig** [comment]
With both SDL1 and SDL2 code in place, it makes sense to me to be able to force one or the other.

Regarding specific flags, I'm inclined to start by looking at SDL's own Autotools-extension script to see:

**Comment by DavidLudwig** [comment]
Update: SDL's latest Autotools script, sdl2.m4, doesn't appear to deal with both SDL1 and SDL2, only SDL2.

**Comment by rickyzhang82** [comment]
Why do you need SDL build script? If you can check the existence of SDL and the version of SDL, that should be good enough. You don't have to build SDL from scratch in BII.

**Comment by DavidLudwig** [comment]
I'm not referring to a script that builds SDL, but rather an Autotools compatible file, which declares function(s) that help to detect an existing installation of SDL, along with commonly used command line options for a configure script.

**Comment by rickyzhang82** [comment]
It looks like you already figured it out in https://hg.libsdl.org/SDL/file/default/sdl2.m4

TBH, I don't know too much about autotools. But it seems that BII configure.ac uses pkg-config to determine SDL version:

```bash
 302   if [[ "x$ac_cv_framework_SDL" = "xno" ]]; then
 303    PKG_CHECK_MODULES([sdl], [sdl >= 1.2], [
 304      CFLAGS="$CFLAGS $sdl_CFLAGS"
 305      CXXFLAGS="$CXXFLAGS $sdl_CFLAGS"
 306      LIBS="$LIBS $sdl_LIBS"
 307    ], [
 308      WANT_SDL=no
 309    ])
 310   fi
```

It doesn't include sdl.m4 in BII aclocal.m4. So you may be able to use macro PKG_CHECK_MODULES, which use pkg-config to check the existence of SDL and its version as well. I knew that pkg-config works in Linux and Mac OS X.

I understood that autotools is a pain to learn. That's why we have cmake today.

**Comment by DavidLudwig** [comment]
Updates:

- SDL 1.x audio APIs (also compatible with SDL2) restored via https://github.com/DavidLudwig/macemu/commit/22eaa317a860e354980a5b8534db513b2723d980 
- SDL 2.x video code moved to video_sdl2.cpp, and SDL 1.x video_sdl.cpp restored, via https://github.com/DavidLudwig/macemu/commit/f8682679c23d90d55797f5a9702e09c619b1994f
- added compile-time check for SDL version, inside video_sdl*.cpp, via: https://github.com/DavidLudwig/macemu/commit/a646f6dc3f70fbc6d172de0d012f090412acf1a2
- make build scripts refer to both video_sdl.cpp and video_sdl2.cpp, via https://github.com/DavidLudwig/macemu/commit/8940880794d87e3f545a49ad13de928c9850f3dd
- minor, video_sdl*.cpp header-comment cleanups / clarifications, via https://github.com/DavidLudwig/macemu/commit/68ee5f23f9c989cedb0d65dc84f9118ccb284f8b

**Comment by DavidLudwig** [comment]
Still to-do:

- autotools updates (thanks for the tips, @rickyzhang82 !)
- make sure SDL 1.x can be forced via Autotools' configure script (on systems with both SDL 1.x and 2.x)
- testing!

**Comment by DavidLudwig** [comment]
More updates:
* on non-OSX hosts, make autoconf fall-back to SDL 1.x, if SDL 2.x cannot be found: https://github.com/DavidLudwig/macemu/commit/1c0e8655dcefad632a8c0d93a94ca271070f38de
* on non-OSX hosts, --with-sdl1 forces the use of SDL 1.x, rather than 2.x: https://github.com/DavidLudwig/macemu/commit/cbda5759bbc4da638beea3183736a6aaad4514a4

**Comment by DavidLudwig** [comment]
Sans further bug reports, I think this is set up now.  Here are the latest updates:

* fixed build errors with Autotools on an OS X host: https://github.com/DavidLudwig/macemu/commit/252890ebd070e6056227dd0323e4295edecb6391
* added --with-sdl1 to SheepShaver's configure script: https://github.com/DavidLudwig/macemu/commit/83096e1ca70608edadcca5e0f81a203d97b78504
