### ISSUE TITLE
Compiled failed in Mac OSX for pre-release 7

### ISSUE THREAD

**Issue by rickyzhang82** [DavidLudwig/macemu#33]
Build commit 4e5e3377f1cfead70e31170a644f1158fe7d35ce (tag: sdl2-prerelease7) through autotools in Mac OS X. It failed:

```
make
g++ -I../MacOSX -I./../include -I./. -I. -I./../CrossPlatform -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DUNALIGNED_PROFITABLE -DX86_64_ASSEMBLY -DOPTIMIZED_FLAGS -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/usr/local/share/BasiliskII\" -g -O2 -D_THREAD_SAFE -I/opt/local/include/SDL2 -I/opt/local/include -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -D_REENTRANT -I/opt/local/include/gtk-2.0 -I/opt/local/lib/gtk-2.0/include -I/opt/local/include/pango-1.0 -I/opt/local/include/gio-unix-2.0/ -I/opt/local/include -I/opt/local/include/cairo -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -c ./../SDL/video_sdl2.cpp -o obj/video_sdl2.o
clang: warning: optimization flag '-fno-merge-constants' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-fno-gcse-sm' is not supported [-Wignored-optimization-argument]
./../SDL/video_sdl2.cpp:782:29: error: expected expression
    sdl_update_video_rect = {0,0,0,0};
                            ^
./../SDL/video_sdl2.cpp:890:29: error: expected expression
    sdl_update_video_rect = {0,0,0,0};
                            ^
2 errors generated.
make: *** [obj/video_sdl2.o] Error 1
```

**Comment by rickyzhang82** [comment]
BTW, do you want to try CI tool?

**Comment by rickyzhang82** [comment]
I added Travis CI in my PR branch. See [here](https://github.com/rickyzhang82/macemu/tree/pr-travis-ci).

I tried to let it build in both Linux and Mac OSX. But I don't know why Mac OS X env is so slow to start. It may spend time in building SDL and GTK+ from homebrew. So in the end I have to remove Mac OS X build environment.

To resolve the problem above automatically, we need to figure out how to automate build in Mac OS X easily.

**Comment by DavidLudwig** [comment]
I fixed this shortly after releasing PR7, via a new commit, https://github.com/DavidLudwig/macemu/commit/7a52abd378f88ed50b40b65e5ecda4eaf15a13f5

CI does sound interesting, however, I would be more interested in trying to get this setup for the main, Basilisk II + SheepShaver repo, at this point.

**Comment by DavidLudwig** [comment]
Thanks for the bug report on this!

**Comment by DavidLudwig** [comment]
I could see CI being worth it at this point though.  I'll give it some thought + research.

**Comment by rickyzhang82** [comment]
I will send a PR to upstream but this require repo owner setup.
